### ISSUE TITLE
Bad registration request.

### ISSUE THREAD

**Issue by hadmut** [gutschke/fido-u2f-nginx-lua#2]
Seems as if the example code is not compatible with the current chrome releases, I just get 

„Bad registration request.“ 

on the browser side. I haven't done enough debugging yet to find the precise reason.

**Comment by hadmut** [comment]
BTW, the problem occurs before the browser connects to the u2f token, even without a token being present.

**Comment by gutschke** [comment]
I just double-checked on my own computer and with an up-to-date copy of Chrome, and things still work just fine.

If you encounter an error this early in the process, it almost certainly points to a misconfiguration of the NGINX component of this demo. It admittedly is a little tricky to install, as NGINX doesn't have a great way to package additional components. So, my best advice is to double-check everything and to see if there are any messages in the NGINX error.log.

Maybe, there is a problem with the LUA code?

Also, and I don't think you have quite made is this far yet, make sure that you are running a memcached. You probably won't need, once you write your own U2F support for whatever code you run in production, but the demo uses memcached to store credentials across sessions.
